### ISSUE TITLE
How do I set selected/checked value?

### ISSUE THREAD

**Issue by ermauliks** [yapplabs/ember-radio-button#17] opened 2015-06-24 08:09 UTC
When I load app (in browser) its not keeping radio-button (by default) value selected. Any work around?

`{{#radio-button checked="checked" class="clusters__size-filter-label" value="size" groupValue=size changed="filterChanged"}} Size {{/radio-button}}`

   ` {{#radio-button class="clusters__size-filter-label" value="volume" groupValue=size changed="filterChanged"}} Volume {{/radio-button}}`

**Comment by raycohen** [comment] 2015-07-06 04:30
Sorry for the delayed response.  I think the issue is that we don't support setting the `checked` attribute initially the way you have `checked="checked"` because that will clobber the property that is used internally to track `value` and `groupValue`

What happens if you remove `checked="checked"` ?

**Comment by bosworthco** [comment] 2015-09-08 04:52
Hi, very useful addon! However this doesn't really answer the question. 

Is a default 'Checked' state something that is going to be added into the functionality in the future?

**Comment by raycohen** [comment] 2015-09-08 13:41
The checked state is computed based on comparing the `value` assigned to the radio-button component and the `groupValue` that is passed in.  When they match, the radio button will be checked.

If that isn't what you want, can you give me more information on the situation you're trying to handle?

**Comment by cmccand** [comment] 2015-09-30 20:46
Hi, thanks for making this. Question: if I want to grab the value of the input on the changed action, how do I access it? I'm trying to get it with jQuery and not having success...

Thanks!

**Comment by raycohen** [comment] 2015-09-30 20:51
@cmccand When you're handling the `changed` action, the `groupValue` property of the radio button components should be updated with the new value.

**Comment by cmccand** [comment] 2015-09-30 21:02
@raycohen Ok, but I'm having trouble getting to the new value at all - for instance, I have the value attribute set to equal the number 30, and the other two buttons are set to 60 and 90, and I need to be able to grab that value and store it...so on the action I'm just trying to console log the value to make sure I know how to get to it...Hope that makes sense (I'm pretty new to this)

**Comment by raycohen** [comment] 2015-09-30 21:18
@cmccand if you can share a little of your code, the template file and action handler, I may have an easier time pointing you in the right direction

**Comment by cmccand** [comment] 2015-09-30 22:19
I think I have it now, setting the groupValue=value as you said did what I was looking for. Thank you!

**Closed** 2015-10-01 18:47 UTC
